const express=require("express");
const morgan=require("morgan");
const authRouter =require("./routes/authroute");
const cookieParsher=require('cookie-parser');
const app=express();
app.use(express.json());
app.use(morgan('dev'));
app.use(cookieParsher());
app.use("/api/auth",authRouter);
module.exports=app;